FROM cube-sandbox-image.tencentcloudcr.com/opensource/tencentos4-minimal:4.4-v20250331
  

WORKDIR /work

RUN yum install -y \
    util-linux \
    busybox \
    gawk \
    gcc \
    gcc-c++ \
    make \
    pkgconf-pkg-config \
    git \
    curl \
    wget \
    tar \
    gzip \
    bzip2 \
    xz \
    zip \
    unzip \
    patch \
    diffutils \
    findutils \
    grep \
    sed \
    less \
    tree \
    jq \
    openssh-clients \
    ca-certificates \
    which \
    vim \
    sudo \
    lsof \
    procps-ng \
    htop \
    man-db \
    bind-utils \
    iputils \
    traceroute \
    mtr \
    iproute \
    net-tools \
    tcpdump \
    nmap-ncat \
    openssl \
    telnet \
    whois \
    iperf3 \
    sysstat \
    strace \
    ltrace

CMD ["bash"]
